#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────



# Puts the frontend on Cloudflare Pages, deployed by .github/workflows/deploy.yml after
# every backend rollout, which makes the site public. The Pages Function forwards /api to
# the backend (ADR-0011), at an origin set on the Pages project and never in the repo.
# Run deploy/setup-ci.sh first, and run this once deploy.yml's frontend job is on main.
# Run from anywhere; it works from the repo root.

TOTAL_STAGES=9
REGION=us-east-1 # where setup-billing.sh put the stack
STACK=pillfacts
SEARCH="/api/search?q=ibuprofen"
cd "$(dirname "$0")/.."

# stop ends the wizard at a "no", saying so. Every stage is safe to repeat.
stop() {
  printf '\n'
  warn "Stopped at stage $_STAGE_INDEX. Run deploy/setup-frontend.sh again to carry on."
  exit 1
}

# stack_output KEY prints one of the stack's outputs.
stack_output() {
  aws cloudformation describe-stacks --region "$REGION" --stack-name "$STACK" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

# cloudflare PATH calls Cloudflare's API with the token and prints the JSON. The token
# goes in through a file descriptor, never an argument, where a process list shows it.
cloudflare() {
  curl -s -H @<(printf 'Authorization: Bearer %s\n' "$CLOUDFLARE_API_TOKEN") \
    "https://api.cloudflare.com/client/v4$1"
}

# succeeded reads Cloudflare's JSON on stdin and succeeds if it says the call did.
succeeded() {
  python3 -c 'import json, sys; sys.exit(0 if json.load(sys.stdin).get("success") else 1)' 2>/dev/null
}

# wrangler ARGS... runs the wrangler deploy.yml deploys with against the account, with
# the token from the environment.
wrangler() {
  CLOUDFLARE_API_TOKEN="$CLOUDFLARE_API_TOKEN" CLOUDFLARE_ACCOUNT_ID="$ACCOUNT_ID" \
    deploy/wrangler/node_modules/.bin/wrangler "$@"
}

# status_of FAMILY prints the status /api/search answers over IPv4 (4) or IPv6 (6), or 000.
status_of() {
  curl "-$1" -s -o /dev/null -w '%{http_code}' --max-time 15 "$SITE_URL$SEARCH" || true
}

# rerun_failed reruns the run's failed jobs and waits until they've started, since until
# then gh run watch reports the failure being rerun.
rerun_failed() {
  gh run rerun "$RUN" --failed
  until [[ "$(gh run view "$RUN" --json status --jq .status)" != completed ]]; do sleep 3; done
}

# show_failure prints the end of the failed step's log, then asks whether to rerun.
show_failure() {
  gh run view "$RUN" --log-failed | tail -n 40 | sed 's/^/    /'
  confirm "Fixed it? Rerun the failed jobs?" || stop
}

# watch_run shows the run until it ends, prints its summary if it failed, and succeeds if it passed.
watch_run() {
  gh run watch "$RUN" --exit-status --interval 10 && return 0
  gh run view "$RUN" | sed 's/^/    /'
  return 1
}

banner "Pill-Facts frontend on Cloudflare Pages"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check aws, gh and node"
until aws sts get-caller-identity >/dev/null 2>&1; do
  warn "aws isn't signed in. In another terminal run 'aws configure' (or 'aws sso login')"
  note "with a user that can read the stack and describe EC2 instances."
  pause "Press Enter to check again"
done
say "aws is signed in to account $(aws sts get-caller-identity --query Account --output text)."
until gh auth status >/dev/null 2>&1; do
  warn "gh isn't signed in. In another terminal run 'gh auth login'."
  pause "Press Enter to check again"
done
REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
say "gh is signed in for $REPO."
until command -v npm >/dev/null 2>&1; do
  warn "npm isn't installed. Install Node.js 24, which comes with it."
  pause "Press Enter to check again"
done
npm ci --ignore-scripts --silent --prefix deploy/wrangler
say "wrangler $(wrangler --version) is installed."
until [[ -n "$(gh variable get PILLFACTS_BACKEND_INSTANCE 2>/dev/null)" ]]; do
  warn "The backend isn't deployed from CI yet. Run deploy/setup-ci.sh first."
  pause "Press Enter to check again"
done
until gh api -H 'Accept: application/vnd.github.raw' \
  "repos/$REPO/contents/.github/workflows/deploy.yml?ref=main" 2>/dev/null | grep -q 'pages deploy'; do
  warn "deploy.yml on main has no frontend job yet. Merge it first."
  pause "Press Enter to check again"
done
say "deploy.yml on main deploys the frontend."
confirm "Is that the AWS account Pill-Facts runs in, and the right repo?" || stop

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create a Cloudflare API token"
say "CI deploys with a token that can edit Pages projects and do nothing else. Cloudflare"
say "shows a token once, so a re-run needs a new one: 'Roll' the old token on that page."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Sign up or sign in. Click 'Create Token', then 'Create Custom Token' → 'Get started'."
step "Name it pill-facts-deploy."
step "Permissions: Account → Cloudflare Pages → Edit."
step "Account Resources: Include → your account. Leave the rest as it is."
step "Click 'Continue to summary', then 'Create Token', and copy the token."
while true; do
  ask_secret CLOUDFLARE_API_TOKEN "Paste the token (hidden):"
  cloudflare /user/tokens/verify | succeeded && break
  warn "Cloudflare doesn't accept that token. Copy it again."
done
say "Cloudflare accepts the token."
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Find the account ID"
ACCOUNT_ID=$(gh variable get CLOUDFLARE_ACCOUNT_ID 2>/dev/null || true)
if [[ -n "$ACCOUNT_ID" ]] && cloudflare "/accounts/$ACCOUNT_ID/pages/projects" | succeeded &&
  confirm "Keep the account already recorded, $ACCOUNT_ID?"; then
  say "Keeping it."
else
  open_url "https://dash.cloudflare.com/"
  step "Open your account. Its menu (⋯ beside the account name) has 'Copy account ID'."
  while true; do
    ask ACCOUNT_ID "Paste the account ID:"
    cloudflare "/accounts/$ACCOUNT_ID/pages/projects" | succeeded && break
    warn "The token can't reach Pages in that account. Check the ID, and the token's account."
  done
fi
say "The token can manage Pages in account $ACCOUNT_ID."
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Create the Pages project"
PROJECT=$(gh variable get PILLFACTS_PAGES_PROJECT 2>/dev/null || true)
PROJECT=${PROJECT:-pill-facts}
if cloudflare "/accounts/$ACCOUNT_ID/pages/projects/$PROJECT" | succeeded; then
  say "The Pages project $PROJECT already exists."
else
  say "This creates the Pages project $PROJECT. CI deploys main to it as production."
  confirm "Create it now?" || stop
  wrangler pages project create "$PROJECT" --production-branch main || stop
fi
# CI deploys with --branch main, which is a preview on a project whose production is
# another branch, and then the check would test the old production.
read -r SUBDOMAIN PRODUCTION_BRANCH < <(cloudflare "/accounts/$ACCOUNT_ID/pages/projects/$PROJECT" |
  python3 -c 'import json, sys; r = json.load(sys.stdin)["result"]; print(r["subdomain"], r["production_branch"])' \
  2>/dev/null) || { warn "Cloudflare didn't return the project $PROJECT. Check it in the dashboard."; stop; }
if [[ "$PRODUCTION_BRANCH" != main ]]; then
  warn "$PROJECT deploys $PRODUCTION_BRANCH to production, and CI deploys main."
  note "Change it under Settings → Builds & deployments → Production branch, then run this again."
  stop
fi
SITE_URL=https://$SUBDOMAIN
say "The site's public URL is $SITE_URL."
note "Cloudflare picks the subdomain, adding a suffix if $PROJECT.pages.dev is taken."
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Point the Function at the backend"
say "The Pages Function forwards /api to PILLFACTS_ORIGIN. Workers can't fetch a bare IP"
say "address, so it's the instance's public DNS name. Moving the backend off the free tier"
say "means changing this value and nothing else (ADR-0011)."
ORIGIN=http://$(aws ec2 describe-instances --region "$REGION" \
  --instance-ids "$(stack_output BackendInstanceId)" \
  --query 'Reservations[0].Instances[0].PublicDnsName' --output text)
[[ "$ORIGIN" == http://*.amazonaws.com ]] || { warn "The instance has no public DNS name: $ORIGIN"; stop; }
say "The backend is at $ORIGIN."
confirm "Set it on the Pages project, as a secret?" || stop
printf '%s' "$ORIGIN" | wrangler pages secret put PILLFACTS_ORIGIN --project-name "$PROJECT"
note "It applies from the next deploy, which stage 7 runs."
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Tell the workflow where to deploy"
say "The token is a GitHub secret. The rest isn't secret, so it goes in GitHub variables."
set_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
set_var CLOUDFLARE_ACCOUNT_ID "$ACCOUNT_ID"
set_var PILLFACTS_PAGES_PROJECT "$PROJECT"
set_var PILLFACTS_SITE_URL "$SITE_URL"
(( ${#SKIPPED[@]} == 0 )) || { warn "gh couldn't set them. Set them by hand, then run this again."; stop; }
pause "Press Enter to continue"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Run the first deploy"
say "This runs the Deploy workflow on main's latest commit. It rolls the backend out again,"
say "then deploys the frontend and searches through $SITE_URL. It takes a few minutes."
confirm "Run it now?" || stop
# The new run is the first with a higher ID than the last before it.
last_dispatch() {
  gh run list --workflow deploy.yml --event workflow_dispatch --limit 1 \
    --json databaseId --jq '.[0].databaseId // 0'
}
before=$(last_dispatch)
gh workflow run deploy.yml --ref main
RUN=$before
for _ in $(seq 1 40); do
  sleep 3
  RUN=$(last_dispatch)
  (( RUN > before )) && break
done
(( RUN > before )) || { warn "The run hasn't appeared after two minutes. Check the Actions tab."; stop; }
say "Watching $(gh run view "$RUN" --json url --jq .url)"
until watch_run; do
  show_failure
  rerun_failed
  say "Watching the rerun."
done
if [[ "$(gh run view "$RUN" --json jobs --jq '.jobs[] | select(.name | startswith("Deploy the frontend")) | .conclusion')" != success ]]; then
  warn "The run passed without deploying the frontend. It's skipped while"
  warn "PILLFACTS_PAGES_PROJECT is unset: check the repo's variables."
  stop
fi
say "The frontend is deployed, and $SITE_URL searches through the backend."
pause "Press Enter to continue"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Check readers don't share a rate limit"
say "The backend counts its rate limit by the last X-Forwarded-For entry, which the Function"
say "sets to the reader's address. If Cloudflare appended one of its own on the way out,"
say "every reader would share one bucket. This spends this machine's burst over IPv4, then"
say "checks a second address isn't refused."
confirm "Run the check?" || stop
sent=0
until status=$(status_of 4); [[ "$status" == 429 ]]; do
  [[ "$status" != 000 ]] || { warn "$SITE_URL can't be reached over IPv4."; stop; }
  (( ++sent < 200 )) || { warn "200 searches over IPv4 and no 429. Is the rate limit on?"; stop; }
done
say "Refused over IPv4 after $sent searches."
# The bucket gets a search back every 10 seconds, so one search from a shared bucket can
# still pass. Three in a row can't.
second=200
for _ in 1 2 3; do
  status=$(status_of 6)
  [[ "$status" == 200 ]] || { second=$status; break; }
done
if [[ "$second" == 000 ]]; then
  say "This machine has no IPv6, so the second address is your phone. Meanwhile this keeps"
  say "searching over IPv4, so a shared bucket stays empty."
  while true; do status_of 4 >/dev/null; sleep 1; done &
  draining=$!
  trap 'kill "$draining" 2>/dev/null' EXIT
  step "Turn Wi-Fi off on your phone, so it uses mobile data."
  step "Open $SITE_URL on it and search for ibuprofen."
  if confirm "Did results load, rather than 'a lot of requests from your connection'?"; then
    second=200
  fi
  kill "$draining"
  trap - EXIT
fi
if [[ "$second" == 200 ]]; then
  say "A second address isn't refused, so each reader gets a bucket of their own."
else
  warn "A second address was refused too (${second/000/on the phone}): every reader shares one bucket."
  note "Cloudflare added to X-Forwarded-For. frontend/proxy/forward.ts and the backend's"
  note "ClientAddress need to agree on another header before the site is safe to share."
  confirm "Carry on anyway?" || stop
fi
pause "Press Enter to continue"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Open the site"
open_url "$SITE_URL/drug-concepts/5640"
step "Check a deep link loads: ibuprofen's page, with its labelling."
step "Search for something from the landing page."
note "From now on every commit on main that passes CI deploys the backend, then this."
pause "Press Enter to finish"

finish
