#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# The backend on an EC2 t3.micro against Neon (ADR-0009), with its secrets in SSM
# Parameter Store and nowhere else: not in the repo, not in a local .env. Then one rollout
# by hand. Run deploy/setup-billing.sh first, since this updates the stack it created.
# Run from anywhere; it works from the repo root.

TOTAL_STAGES=8
REGION=us-east-1 # where setup-billing.sh put the stack, and where the Neon project goes
STACK=pillfacts
cd "$(dirname "$0")/.."

# stop ends the wizard at a "no", saying so. Anything but y is a no, Enter included.
# Every finished stage is safe to repeat: a re-run keeps stored secrets if you let it,
# finds the stack unchanged and the instance online, and gets back here in a minute.
stop() {
  printf '\n'
  warn "Stopped at stage $_STAGE_INDEX. Run deploy/setup-backend.sh again to carry on."
  exit 1
}

# stack_output KEY prints one of the stack's outputs.
stack_output() {
  aws cloudformation describe-stacks --region "$REGION" --stack-name "$STACK" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

# have_parameters NAME... succeeds when every named SSM parameter already exists.
have_parameters() {
  local found
  found=$(aws ssm get-parameters --region "$REGION" --names "$@" \
    --query 'length(Parameters)' --output text 2>/dev/null) || return 1
  [[ "$found" == "$#" ]]
}

# PUT_SECURE is Python that defines put(name, value), which stores value as the
# SecureString name. A secret never goes in an argument, where a process list shows it.
# The CLI won't read JSON from a pipe (file:///dev/stdin arrives empty), so the request
# goes to a file only this user can read, removed as soon as the CLI has read it.
PUT_SECURE='import json, os, subprocess, sys, tempfile
def put(name, value):
    fd, path = tempfile.mkstemp(suffix=".json")  # mode 600
    try:
        with os.fdopen(fd, "w") as request:
            json.dump({"Name": name, "Value": value, "Type": "SecureString", "Overwrite": True}, request)
        subprocess.run(["aws", "ssm", "put-parameter", "--region", os.environ["REGION"],
                        "--cli-input-json", "file://" + path], check=True, stdout=subprocess.DEVNULL)
    finally:
        os.remove(path)
    print("  stored " + name + " in Parameter Store")
'

# put_secure NAME stores stdin as the SecureString NAME.
put_secure() {
  REGION="$REGION" python3 -c "$PUT_SECURE"'
put(sys.argv[1], sys.stdin.read())' "$1"
}

# run_on_box COMMAND... runs shell commands on the instance over SSM Run Command, waits
# for them however long they take, and prints what they printed. It fails if they did.
# The commands are kept in Run Command's history, so they must never hold a secret.
run_on_box() {
  local instance command_id status=Pending polls=0
  instance=$(stack_output BackendInstanceId)
  command_id=$(aws ssm send-command --region "$REGION" --instance-ids "$instance" \
    --document-name AWS-RunShellScript --comment "deploy/setup-backend.sh" \
    --parameters "$(python3 -c 'import json, sys; print(json.dumps({"commands": sys.argv[1:]}))' "$@")" \
    --query Command.CommandId --output text) || return 1
  # The built-in waiter gives up after 100 seconds, too soon for a Spring start here.
  while [[ "$status" =~ ^(Pending|InProgress|Delayed|Cancelling)$ ]]; do
    (( polls++ < 180 )) || { warn "Gave up after 15 minutes: Run Command $command_id"; return 1; }
    sleep 5
    status=$(aws ssm get-command-invocation --region "$REGION" --command-id "$command_id" \
      --instance-id "$instance" --query Status --output text 2>/dev/null || echo Pending)
  done
  for stream in StandardOutputContent StandardErrorContent; do
    aws ssm get-command-invocation --region "$REGION" --command-id "$command_id" \
      --instance-id "$instance" --query "$stream" --output text | sed 's/^/    /'
  done
  [[ "$status" == Success ]]
}

banner "Pill-Facts backend on EC2 and Neon"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check aws, gh and docker"
until aws sts get-caller-identity >/dev/null 2>&1; do
  warn "aws isn't signed in. In another terminal run 'aws configure' (or 'aws sso login')"
  note "with a user that can update CloudFormation stacks, IAM roles, EC2 and SSM."
  pause "Press Enter to check again"
done
say "aws is signed in to account $(aws sts get-caller-identity --query Account --output text)."
until aws cloudformation describe-stacks --region "$REGION" --stack-name "$STACK" >/dev/null 2>&1; do
  warn "There's no '$STACK' stack in $REGION. Run deploy/setup-billing.sh first."
  pause "Press Enter to check again"
done
until [[ "$(gh auth status 2>&1)" == *write:packages* ]]; do
  warn "gh needs to push to GitHub's container registry. In another terminal run:"
  note "    gh auth refresh -h github.com -s write:packages"
  pause "Press Enter to check again"
done
OWNER=$(gh repo view --json owner --jq .owner.login | tr '[:upper:]' '[:lower:]')
REPO_URL=$(gh repo view --json url --jq .url)
say "gh is signed in for $REPO_URL."
until docker info >/dev/null 2>&1; do
  warn "Docker isn't running. Start Docker Desktop."
  pause "Press Enter to check again"
done
say "Docker is running."
confirm "Is that the AWS account Pill-Facts runs in, and the right repo?" || stop

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the Neon database"
DB_PARAMETERS=(/pillfacts/db-url /pillfacts/db-username /pillfacts/db-password)
if have_parameters "${DB_PARAMETERS[@]}" && ! confirm "The database is already in Parameter Store. Replace it?"; then
  say "Keeping the database already stored."
else
  open_url "https://console.neon.tech/app/projects"
  step "Click 'New project'. Name it pillfacts."
  step "Cloud provider AWS, region 'AWS US East 1 (N. Virginia)', beside the instance."
  step "Postgres version: the newest offered. Click Create."
  step "On the project dashboard click 'Connect'. Turn 'Connection pooling' OFF."
  note "Flyway takes a session-level lock that pooled (-pooler) connections break."
  step "Copy the connection string, the one starting postgresql://"
  while true; do
    ask_secret NEON_CONNECTION_STRING "Paste the connection string (hidden):"
    # Parsed and stored in one go, so the password never lands in a shell variable of its
    # own. A JDBC URL carries no credentials; the user and password are parameters apart.
    if printf '%s' "$NEON_CONNECTION_STRING" | REGION="$REGION" python3 -c "$PUT_SECURE"'
from urllib.parse import unquote, urlsplit

url = urlsplit(sys.stdin.read().strip().strip("\x27\""))
host = url.hostname or ""
def refuse(why):
    print("  " + why, file=sys.stderr)
    sys.exit(1)
if url.scheme not in ("postgres", "postgresql") or not host.endswith(".neon.tech"):
    refuse("That is not a Neon connection string (postgresql://...neon.tech/...).")
if host.split(".")[0].endswith("-pooler"):
    refuse("That is the pooled connection. Turn Connection pooling off and copy it again.")
if ".us-east-1." not in host:
    refuse("That project is not in AWS us-east-1. Create it there, beside the instance.")
if not (url.username and url.password and url.path.strip("/")):
    refuse("The string is missing its user, password or database name.")
port = f":{url.port}" if url.port else ""
values = {
    "/pillfacts/db-url": f"jdbc:postgresql://{host}{port}/{url.path.strip(chr(47))}?sslmode=require",
    "/pillfacts/db-username": unquote(url.username),
    "/pillfacts/db-password": unquote(url.password),
}
for name, value in values.items():
    put(name, value)
'; then
      break
    fi
    warn "That wasn't stored whole. Copy the string again."
  done
  unset NEON_CONNECTION_STRING
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Store the openFDA API key"
say "Without a key the backend shares openFDA's 1,000 unkeyed requests a day."
if have_parameters /pillfacts/openfda-api-key && ! confirm "A key is already in Parameter Store. Replace it?"; then
  say "Keeping the key already stored."
else
  open_url "https://open.fda.gov/apis/authentication/"
  step "Under 'Get your API key', enter your email and submit. The key arrives by email."
  OPENFDA_API_KEY=""
  while [[ -z "$OPENFDA_API_KEY" ]]; do
    ask_secret OPENFDA_API_KEY "Paste the openFDA API key (hidden):"
  done
  printf '%s' "$OPENFDA_API_KEY" | put_secure /pillfacts/openfda-api-key
  unset OPENFDA_API_KEY
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Deploy the instance"
say "The template allows port 80 from Cloudflare's published ranges and nothing else."
say "Checking that list against https://www.cloudflare.com/ips-v4 ..."
published=$(curl -sf https://www.cloudflare.com/ips-v4 | tr -d '\r' | grep . | sort) || {
  warn "Couldn't fetch Cloudflare's list. Check your connection and run this again."
  exit 1
}
templated=$(grep -oE 'CidrIp: [0-9./]+' deploy/aws.yaml | cut -d' ' -f2 | sort)
if [[ "$published" != "$templated" ]]; then
  warn "deploy/aws.yaml no longer matches Cloudflare's list. Fix the template first:"
  diff <(printf '%s\n' "$templated") <(printf '%s\n' "$published") | sed 's/^/    /' || true
  exit 1
fi
say "They match."
say "This updates the '$STACK' stack: a t3.micro (Amazon Linux 2023, Docker, 1GB swap),"
say "its role, its security group and an Elastic IP. No key pair, no port 22."
note "All of it is inside the free tier while that lasts (ADR-0009)."
confirm "Deploy the stack now?" || stop
aws cloudformation deploy --region "$REGION" --stack-name "$STACK" \
  --template-file deploy/aws.yaml --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM
INSTANCE=$(stack_output BackendInstanceId)
ORIGIN_HOST=$(aws ec2 describe-instances --region "$REGION" --instance-ids "$INSTANCE" \
  --query 'Reservations[0].Instances[0].PublicDnsName' --output text)
say "Deployed $INSTANCE at $ORIGIN_HOST."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Wait for the instance to reach SSM"
say "A new instance installs Docker, then its SSM agent checks in. A few minutes."
until [[ "$(aws ssm describe-instance-information --region "$REGION" \
  --filters "Key=InstanceIds,Values=$INSTANCE" \
  --query 'InstanceInformationList[0].PingStatus' --output text)" == Online ]]; do
  note "Not yet. Checking again in 15 seconds."
  sleep 15
done
until run_on_box 'docker info --format "Docker {{.ServerVersion}}"' 'swapon --show' >/dev/null 2>&1; do
  note "SSM is up; Docker is still installing. Checking again in 15 seconds."
  sleep 15
done
say "$INSTANCE is online over SSM with Docker running."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Build the backend image and push it"
IMAGE="ghcr.io/$OWNER/pill-facts-backend:manual-$(git rev-parse --short HEAD)"
say "This builds backend/ for the instance's x86 CPU and pushes it to GitHub's registry as"
say "  $IMAGE"
note "A temporary tag. From the next slice, CI pushes one per commit."
note "On an Apple-silicon Mac the build runs emulated and takes several minutes."
confirm "Build and push it now?" || stop
gh auth token | docker login ghcr.io -u "$(gh api user --jq .login)" --password-stdin >/dev/null
docker buildx build --platform linux/amd64 --push \
  --label "org.opencontainers.image.source=$REPO_URL" \
  -t "$IMAGE" backend
say "Pushed."
# anonymous_pull succeeds when the image can be pulled without signing in. While the
# package is private, GHCR refuses the anonymous token, so the request fails quietly.
# Public, so the instance pulls with no credentials (#46 is about making it private). The image holds no secret; those are
# read from Parameter Store when it runs.
anonymous_pull() {
  local token
  token=$(curl -sf "https://ghcr.io/token?scope=repository:$OWNER/pill-facts-backend:pull" |
    python3 -c 'import json, sys; print(json.load(sys.stdin)["token"])' 2>/dev/null) || return 1
  curl -sf -o /dev/null -H "Authorization: Bearer $token" \
    -H 'Accept: application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.oci.image.manifest.v1+json' \
    "https://ghcr.io/v2/$OWNER/pill-facts-backend/manifests/${IMAGE##*:}"
}
if ! anonymous_pull; then
  say "The package is private, so the instance can't pull it. Make it public:"
  open_url "https://github.com/users/$OWNER/packages/container/pill-facts-backend/settings"
  step "Under 'Danger Zone', click 'Change visibility', choose Public."
  step "Type pill-facts-backend to confirm, then click the button."
  until { pause "Press Enter once it's public"; anonymous_pull; }; do
    warn "It still can't be pulled without signing in."
  done
fi
say "Anyone can pull it, and the instance needs no registry credentials."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Roll it out"
say "This sends deploy/ec2/rollout.sh to $INSTANCE over SSM Run Command. It reads"
say "/pillfacts/* into a root-only env file, pulls the image, replaces the container and"
say "waits for port 80. The first start also runs the Flyway migrations against Neon."
confirm "Roll out $IMAGE now?" || stop
rollout=$(base64 < deploy/ec2/rollout.sh | tr -d '\n')
until run_on_box "echo $rollout | base64 -d > /tmp/rollout.sh" "bash /tmp/rollout.sh $IMAGE"; do
  warn "The rollout failed. Its output is above."
  confirm "Try it again?" || stop
done
say "The backend is up."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Check what it uses and who can reach it"
say "A few searches and Drug Concept pages, run on the instance itself, then its memory."
# shellcheck disable=SC2016 # expanded by the instance's shell, not this one
run_on_box '
for q in ibuprofen metformin lisinopril atorvastatin cetirizine; do
  rxcui=$(curl -s "http://localhost/api/search?q=$q" | python3 -c "import json, sys; c = json.load(sys.stdin)[\"candidates\"]; print(c[0][\"rxcui\"] if c else \"\")")
  printf "%-14s search ok, rxcui %s, drug concept %s\n" "$q" "${rxcui:-none}" \
    "$([ -n "$rxcui" ] && curl -s -o /dev/null -w "%{http_code}" "http://localhost/api/drug-concepts/$rxcui")"
done
echo
docker stats --no-stream --format "table {{.Name}}\t{{.MemUsage}}\t{{.MemPerc}}\t{{.CPUPerc}}"
echo
free -m' || warn "The checks failed. Their output is above."
step "MEM USAGE should sit well under its 768MiB limit, and free -m should show room left."
pause "Press Enter once you've read it"
say "Now from here, outside Cloudflare: the instance should not answer at all."
if curl -s -o /dev/null --max-time 5 "http://$ORIGIN_HOST/"; then
  warn "http://$ORIGIN_HOST/ answered this machine. The security group isn't holding."
  exit 1
fi
say "http://$ORIGIN_HOST/ timed out, as it should. Only Cloudflare reaches it."
note "Next, deploy/setup-frontend.sh points PILLFACTS_ORIGIN at http://$ORIGIN_HOST."
pause "Press Enter to finish"

finish
