#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Hands the backend's rollouts to .github/workflows/deploy.yml: every commit on main that
# CI passes is built, pushed to GHCR and rolled out over SSM, with no AWS key anywhere.
# Run deploy/setup-backend.sh first, and run this once deploy.yml is on main, since only
# main can assume the deploy role. Run from anywhere; it works from the repo root.

TOTAL_STAGES=6
REGION=us-east-1 # where setup-billing.sh put the stack
STACK=pillfacts
PACKAGE=pill-facts-backend
cd "$(dirname "$0")/.."

# stop ends the wizard at a "no", saying so. Every stage is safe to repeat.
stop() {
  printf '\n'
  warn "Stopped at stage $_STAGE_INDEX. Run deploy/setup-ci.sh again to carry on."
  exit 1
}

# stack_output KEY prints one of the stack's outputs.
stack_output() {
  aws cloudformation describe-stacks --region "$REGION" --stack-name "$STACK" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

# anonymous_pull TAG succeeds when the image can be pulled without signing in. While the
# package is private, GHCR refuses the anonymous token, so the request fails quietly.
anonymous_pull() {
  local token
  token=$(curl -sf "https://ghcr.io/token?scope=repository:$OWNER/$PACKAGE:pull" |
    python3 -c 'import json, sys; print(json.load(sys.stdin)["token"])' 2>/dev/null) || return 1
  curl -sf -o /dev/null -H "Authorization: Bearer $token" \
    -H 'Accept: application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.oci.image.manifest.v1+json' \
    "https://ghcr.io/v2/$OWNER/$PACKAGE/manifests/$1"
}

# watch_run waits for the run to end, then prints its summary and succeeds if it passed.
watch_run() {
  gh run watch "$RUN" --exit-status --interval 10 >/dev/null 2>&1 && return 0
  gh run view "$RUN" | sed 's/^/    /'
  return 1
}

# rerun_failed reruns the run's failed jobs and waits until they've started, since until
# then gh run watch reports the failure being rerun.
rerun_failed() {
  gh run rerun "$RUN" --failed
  until [[ "$(gh run view "$RUN" --json status --jq .status)" != completed ]]; do sleep 3; done
}

# show_failure prints the end of the failed step's log, then asks whether to rerun.
show_failure() {
  gh run view "$RUN" --log-failed | tail -n 40 | sed 's/^/    /'
  confirm "Fixed it? Rerun the failed jobs?" || stop
}

banner "Pill-Facts backend deployed from CI"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check aws and gh"
until aws sts get-caller-identity >/dev/null 2>&1; do
  warn "aws isn't signed in. In another terminal run 'aws configure' (or 'aws sso login')"
  note "with a user that can update CloudFormation stacks and IAM roles."
  pause "Press Enter to check again"
done
say "aws is signed in to account $(aws sts get-caller-identity --query Account --output text)."
until [[ "$(stack_output BackendInstanceId 2>/dev/null)" == i-* ]]; do
  warn "The '$STACK' stack in $REGION has no backend instance. Run deploy/setup-backend.sh first."
  pause "Press Enter to check again"
done
until [[ "$(gh auth status 2>&1)" == *packages* ]]; do
  warn "gh needs to read GitHub's container registry. In another terminal run:"
  note "    gh auth refresh -h github.com -s read:packages"
  pause "Press Enter to check again"
done
REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
OWNER=$(gh repo view --json owner --jq .owner.login | tr '[:upper:]' '[:lower:]')
say "gh is signed in for $REPO."
until gh api "repos/$REPO/contents/.github/workflows/deploy.yml?ref=main" >/dev/null 2>&1; do
  warn "deploy.yml isn't on main yet. Merge it first: only main can assume the deploy role."
  pause "Press Enter to check again"
done
say "deploy.yml is on main."
confirm "Is that the AWS account Pill-Facts runs in, and the right repo?" || stop

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Add the deploy role to the stack"
say "This updates the '$STACK' stack with a role GitHub Actions on main can assume, through"
say "GitHub's OIDC tokens. All it can do is run a shell script on the backend instance."
# An account holds one provider per issuer. Keep the stack's own, else reuse the account's.
OIDC_PROVIDER=""
stack_provider=$(aws cloudformation list-stack-resources --region "$REGION" --stack-name "$STACK" \
  --query "StackResourceSummaries[?LogicalResourceId=='GitHubOidcProvider'].PhysicalResourceId" \
  --output text)
if [[ -n "$stack_provider" && "$stack_provider" != None ]]; then
  note "The stack already holds GitHub's OIDC provider."
else
  OIDC_PROVIDER=$(aws iam list-open-id-connect-providers \
    --query "OpenIDConnectProviderList[?ends_with(Arn, '/token.actions.githubusercontent.com')].Arn" \
    --output text)
  if [[ -n "$OIDC_PROVIDER" ]]; then
    note "The account already has GitHub's OIDC provider, so the stack reuses it."
    # Made for another project, it may not accept the audience configure-aws-credentials sends.
    if ! aws iam get-open-id-connect-provider --open-id-connect-provider-arn "$OIDC_PROVIDER" \
      --query ClientIDList --output text | tr '\t' '\n' | grep -qx sts.amazonaws.com; then
      warn "It doesn't accept the audience sts.amazonaws.com, which the workflow's tokens carry."
      confirm "Add sts.amazonaws.com to it? Whatever else uses it is unaffected." || stop
      aws iam add-client-id-to-open-id-connect-provider \
        --open-id-connect-provider-arn "$OIDC_PROVIDER" --client-id sts.amazonaws.com
    fi
  else
    note "The account has no GitHub OIDC provider yet, so the stack creates one."
  fi
fi
confirm "Deploy the stack now?" || stop
aws cloudformation deploy --region "$REGION" --stack-name "$STACK" \
  --template-file deploy/aws.yaml --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM \
  --parameter-overrides "GitHubOidcProviderArn=$OIDC_PROVIDER"
DEPLOY_ROLE=$(stack_output DeployRoleArn)
INSTANCE=$(stack_output BackendInstanceId)
say "Deployed. The role is $DEPLOY_ROLE."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Tell the workflow where to deploy"
say "None of these is a secret, so they go in GitHub variables, where the logs show them."
set_var PILLFACTS_AWS_DEPLOY_ROLE "$DEPLOY_ROLE"
set_var PILLFACTS_BACKEND_INSTANCE "$INSTANCE"
set_var PILLFACTS_AWS_REGION "$REGION"
(( ${#SKIPPED[@]} == 0 )) || { warn "gh couldn't set them. Set them by hand, then run this again."; stop; }
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Let the workflow push the image"
if gh api "users/$OWNER/packages/container/$PACKAGE" >/dev/null 2>&1; then
  say "deploy/setup-backend.sh pushed $PACKAGE by hand, so the package is yours, not the"
  say "repo's. The workflow can't push to it until the repo is given write access."
  open_url "https://github.com/users/$OWNER/packages/container/$PACKAGE/settings"
  step "Under 'Manage Actions access', click 'Add Repository' and choose ${REPO#*/}."
  step "Set its role to Write."
  pause "Press Enter once it's added"
else
  say "There's no $PACKAGE package yet. The first run creates it, owned by the repo."
  pause "Press Enter to continue"
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Run the first deploy"
say "This runs the Deploy workflow on main's latest commit: it checks CI passed, builds and"
say "pushes the image, then rolls it out. A Spring start on the t3.micro takes a few minutes."
head=$(gh api "repos/$REPO/commits/main" --jq .sha)
until [[ "$(gh run list --workflow ci.yml --commit "$head" --event push --status success \
  --json databaseId --jq length)" != 0 ]]; do
  warn "CI hasn't passed for main's head, ${head:0:7}, and the workflow deploys nothing else."
  pause "Press Enter once it has passed"
done
confirm "Run it now?" || stop
# The new run is the first with a higher ID than the last before it.
last_dispatch() {
  gh run list --workflow deploy.yml --event workflow_dispatch --limit 1 \
    --json databaseId --jq '.[0].databaseId // 0'
}
before=$(last_dispatch)
gh workflow run deploy.yml --ref main
RUN=$before
for _ in $(seq 1 40); do
  sleep 3
  RUN=$(last_dispatch)
  (( RUN > before )) && break
done
(( RUN > before )) || { warn "The run hasn't appeared after two minutes. Check the Actions tab."; stop; }
say "Watching $(gh run view "$RUN" --json url --jq .url)"
if watch_run; then
  DEPLOYED=true
else
  DEPLOYED=false
  warn "It failed. A new package is private, which fails the rollout: the next stage fixes that."
fi
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Make the image public and finish the deploy"
TAG=$(gh run view "$RUN" --json headSha --jq .headSha)
until $DEPLOYED; do
  failed=$(gh run view "$RUN" --json jobs --jq '[.jobs[] | select(.conclusion == "failure") | .name] | join(", ")')
  if [[ "$failed" == *Build* ]]; then
    warn "The image wasn't pushed. If it says permission_denied, redo stage 4. The log:"
    show_failure
  elif [[ "$failed" == *"Roll it out"* ]] && ! anonymous_pull "$TAG"; then
    say "The instance pulls without credentials, so the package must be public. The image"
    say "holds no secret; those are read from Parameter Store on the instance."
    open_url "https://github.com/users/$OWNER/packages/container/$PACKAGE/settings"
    step "Under 'Danger Zone', click 'Change visibility', choose Public."
    step "Type $PACKAGE to confirm, then click the button."
    until { pause "Press Enter once it's public"; anonymous_pull "$TAG"; }; do
      warn "It still can't be pulled without signing in."
    done
  else
    warn "${failed:-The run} failed. The failed step's log:"
    show_failure
  fi
  rerun_failed
  say "Watching the rerun."
  if watch_run; then DEPLOYED=true; fi
done
say "$OWNER/$PACKAGE:$TAG is running on $INSTANCE."
note "From now on every commit on main that passes CI deploys itself."
pause "Press Enter to finish"

finish
