#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# The two obligations ADR-0009 says the code can't show: a $1 billing alarm that has been
# seen to fire, and the free-tier end date recorded where the weekly workflow
# (.github/workflows/free-tier-expiry.yml) will warn about it. Run from the repo root.

TOTAL_STAGES=6
REGION=us-east-1 # the only region that publishes billing metrics
STACK=pillfacts
cd "$(dirname "$0")/.."

# stack_output KEY prints one of the stack's outputs.
stack_output() {
  aws cloudformation describe-stacks --region "$REGION" --stack-name "$STACK" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

# days_before DATE N prints DATE minus N days as YYYYMMDD, and fails unless DATE is a real
# YYYY-MM-DD. Python, not date(1), so it accepts exactly what check-free-tier-expiry.py does.
days_before() {
  python3 -c 'import datetime, re, sys
assert re.fullmatch(r"\d{4}-\d{2}-\d{2}", sys.argv[1])
d = datetime.date.fromisoformat(sys.argv[1]) - datetime.timedelta(days=int(sys.argv[2]))
print(d.strftime("%Y%m%d"))' "$1" "$2" 2>/dev/null
}

banner "Pill-Facts billing alarm and free-tier expiry"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check aws and gh are signed in"
until aws sts get-caller-identity >/dev/null 2>&1; do
  warn "aws isn't signed in. In another terminal run 'aws configure' (or 'aws sso login')"
  note "with a user that can create CloudFormation stacks, SNS topics and CloudWatch alarms."
  pause "Press Enter to check again"
done
say "aws is signed in to account $(aws sts get-caller-identity --query Account --output text)."
until gh auth status >/dev/null 2>&1; do
  warn "gh isn't signed in. In another terminal run 'gh auth login'."
  pause "Press Enter to check again"
done
say "gh is signed in for $(gh repo view --json nameWithOwner --jq .nameWithOwner)."
confirm "Is that the AWS account Pill-Facts runs in, and the right repo?" || exit 1

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Turn on CloudWatch billing alerts"
say "AWS publishes no billing metric until this is on, so the alarm would never fire."
open_url "https://us-east-1.console.aws.amazon.com/billing/home#/preferences"
step "Sign in as the root user or an IAM user with billing access, if asked."
step "In 'Alert preferences', click Edit."
step "Tick 'Receive CloudWatch billing alerts', then click Update."
note "The metric can take a few hours to appear. The alarm doesn't need it to exist yet."
pause "Press Enter once it's saved"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Deploy the billing alarm"
say "This creates the '$STACK' stack in $REGION from deploy/aws.yaml: an SNS topic that"
say "emails you, and an alarm on estimated charges over \$1. None of it costs anything."
ask PILLFACTS_ALERT_EMAIL "Email address for billing alerts:"
confirm "Deploy the stack now?" || exit 1
aws cloudformation deploy --region "$REGION" --stack-name "$STACK" \
  --template-file deploy/aws.yaml --no-fail-on-empty-changeset \
  --parameter-overrides "AlertEmail=$PILLFACTS_ALERT_EMAIL"
say "Deployed."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Confirm the alert subscription"
say "AWS has emailed $PILLFACTS_ALERT_EMAIL a subscription confirmation."
step "Open the email titled 'AWS Notification - Subscription Confirmation'."
step "Click 'Confirm subscription'."
note "Check spam if it hasn't arrived in a minute or two."
topic=$(stack_output BillingAlertsTopic)
while true; do
  pause "Press Enter once you've clicked it"
  pending=$(aws sns list-subscriptions-by-topic --region "$REGION" --topic-arn "$topic" \
    --query "Subscriptions[?SubscriptionArn=='PendingConfirmation'] | length(@)" --output text)
  [[ "$pending" == "0" ]] && break
  warn "AWS still shows the subscription as pending confirmation."
done
say "Subscription confirmed."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Fire the alarm once"
alarm=$(stack_output BillingAlarmName)
say "This forces '$alarm' into ALARM so you can see the email arrive, then puts it back."
confirm "Fire it now?" || exit 1
aws cloudwatch set-alarm-state --region "$REGION" --alarm-name "$alarm" \
  --state-value ALARM --state-reason "Verifying the alarm fires (deploy/setup-billing.sh)"
step "Wait for an email titled 'ALARM: \"$alarm\" in US East (N. Virginia)'."
until confirm "Did it arrive?"; do
  note "It usually takes under a minute. Check spam, then answer again."
done
aws cloudwatch set-alarm-state --region "$REGION" --alarm-name "$alarm" \
  --state-value OK --state-reason "Verified the alarm fires (deploy/setup-billing.sh)"
say "Verified, and set back to OK."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Record when the free tier ends"
open_url "https://us-east-1.console.aws.amazon.com/billing/home#/freetier"
step "Find the date your free tier ends. On an account opened after 15 July 2025 it's"
step "the end of the free plan; on an older one, 12 months after the account was created."
while true; do
  ask PILLFACTS_FREE_TIER_EXPIRES "End date, as YYYY-MM-DD:"
  PILLFACTS_FREE_TIER_EXPIRES=$(printf '%s' "$PILLFACTS_FREE_TIER_EXPIRES" | tr -d '[:space:]')
  reminder=$(days_before "$PILLFACTS_FREE_TIER_EXPIRES" 30) && break
  # %q shows what was actually read, including any arrow-key or pasted control characters.
  warn "$(printf '%q' "$PILLFACTS_FREE_TIER_EXPIRES") isn't a date like 2027-04-01. Type it fresh."
done
set_var PILLFACTS_FREE_TIER_EXPIRES "$PILLFACTS_FREE_TIER_EXPIRES"
say "The weekly Free-tier expiry workflow fails from 30 days out, and emails you when it does."
step "Now save a calendar reminder for the same day. Check the details, then click Save."
# An all-day event's end date is exclusive, so a one-day reminder ends the day after.
reminder_end=$(days_before "$PILLFACTS_FREE_TIER_EXPIRES" 29)
open_url "https://calendar.google.com/calendar/render?action=TEMPLATE&text=Pill-Facts%3A%20AWS%20free%20tier%20ends%20in%2030%20days&dates=${reminder}/${reminder_end}&details=The%20AWS%20free%20tier%20ends%20on%20${PILLFACTS_FREE_TIER_EXPIRES}.%20Move%20the%20backend%20to%20Koyeb%20(ADR-0009)%2C%20then%20repoint%20the%20Pages%20variable%20PILLFACTS_ORIGIN%20at%20it%20(ADR-0011)."
pause "Press Enter once the event is saved"

finish
